# Generated by Django 4.0.5 on 2022-06-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre cliente')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('mail', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
