# Generated by Django 4.0.5 on 2022-06-25 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bicicletas',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id_ciclo')),
                ('anio', models.IntegerField(max_length=50, verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('idMarca', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de marca')),
                ('nombreMarca', models.CharField(max_length=50, verbose_name='Nombre marca')),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('idModelo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreModelo', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Nombre tipo')),
            ],
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.AddField(
            model_name='bicicletas',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca'),
        ),
        migrations.AddField(
            model_name='bicicletas',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelo'),
        ),
        migrations.AddField(
            model_name='bicicletas',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo'),
        ),
    ]
